### ISSUE TITLE
Secrets loop logs secrets

### ISSUE THREAD

**Issue by sveno1990** [linux-system-roles/podman#112]
The loop in the main.yml logs the podman secret despite the fact that the task itself has the no_log value set. The loop itself still logs the secrets.

- name: Handle secrets
  include_tasks: handle_secret.yml
  loop: "{{ podman_secrets }}"
  loop_control:
    loop_var: __podman_secret_item

**Comment by richm** [comment]
> The loop in the main.yml logs the podman secret despite the fact that the task itself has the no_log value set. The loop itself still logs the secrets.
> 
>     * name: Handle secrets
>       include_tasks: handle_secret.yml
>       loop: "{{ podman_secrets }}"
>       loop_control:
>       loop_var: __podman_secret_item

@sveno1990 Can you try https://github.com/linux-system-roles/podman/pull/113 to see if it addresses the problem?

**Comment by sveno1990** [comment]
Hi @richm,
That solves the issue, Thanks a lot!
