### ISSUE TITLE
Use underscore instead of hyphens in role names in the examples

### ISSUE THREAD

**Issue by linuxnow** [linux-system-roles/podman#115]
In the examples we have:
  roles:
    - linux-system-roles.podman
which does'nt work.

Instead you should put:
  roles:
    - linux_system_roles.podman

It has driven me crazy!

**Comment by richm** [comment]
> In the examples we have: roles: - linux-system-roles.podman which does'nt work.

It definitely works in most contexts e.g. https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/lsr-citool_podman-103-a247353_CentOS-Stream-9_20231223-164956/artifacts/summary.html

* What is the error?
* What version of ansible are you using?
* What is the control node platform?
* What is the managed node platform?

> 
> Instead you should put: roles: - linux_system_roles.podman

Yes, but the linux-system-roles project came well before the restriction on dash `-` characters in role names.  Plus, the restriction only applies to collections, not legacy roles.
You can also use `fedora.linux_system_roles.podman` from the collection - https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/

> 
> It has driven me crazy!
