### ISSUE TITLE
Create volume with podman_quadlet, but the service can't start.

### ISSUE THREAD

**Issue by Aquilamason** [linux-system-roles/podman#118]
I used such a volume file to create a volume for the promtail container:

```
podman_quadlet_specs:
  - file_src: "promtail-data.volume"
  - template_src: "promtail.container.j2"
```
 
The contents of the promtail-data.volume file are only:
`[Volume]`

But when I run the ansible play, the following error is reported:

TASK [ansible-role-podman : Start service] *****************************************************************************************************************
fatal: [my-hostname]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": false,
            "enabled": null,
            "force": null,
            "masked": null,
            "name": "promtail-data.volume",
            "no_block": false,
            "scope": "system",
            "state": "started"
        }
    },
    "msg": "Could not find the requested service promtail-data.volume: host"
}

After looking at the following code for the podman task codes, I see that the value of __podman_service_name is automatically suffixed with .volume.
[podman/tasks/handle_quadlet_spec.yml](https://github.com/linux-system-roles/podman/blob/9a62ed3dcedb8a3bbeb494e774b5de1204054766/tasks/handle_quadlet_spec.yml#L130C16-L130C16)

      else __podman_quadlet_name ~ '.volume'

But according to the [podman-systemd](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#volume-units-volume) documentation, the Volume unit automatically creates service name with the -volume.service suffix.
I added "activate_systemd_unit: false" to quadlet_specs to skip the play to start the service, but I think the code should be changed to:
`    else __podman_quadlet_name ~ '-volume'`

Right?

**Comment by richm** [comment]
What is your control node platform?  ansible version?  managed node platform?

**Comment by richm** [comment]
@Aquilamason can you try https://github.com/linux-system-roles/podman/pull/119?

**Comment by richm** [comment]
#119 merged
