### ISSUE TITLE
podman_host_directories default 0644 mode results in unusable directories

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/podman#20]
By default, the role creates directories with 0644 permissions, which results in directories that cannot be traversed.  Would it be possible to have the role default to using the umask to set the permissions?

**Comment by richm** [comment]
> By default, the role creates directories with 0644 permissions, which results in directories that cannot be traversed. Would it be possible to have the role default to using the umask to set the permissions?

See https://github.com/linux-system-roles/podman/pull/21 - the short answer is "no, it is not possible to have the role default to using the umask to set the permissions"

**Comment by richm** [comment]
> If we can't use the umask, is there a reason we are defaulting specifically to 0644 permissions? It seems unusual to create a directory without the execute permission.

There is no reason.  I removed the default mode.  Now it will use whatever the Ansible `file` module uses when creating a directory without a mode.  It does not appear to use `umask` as set in ~/.bashrc or ~/.bash_profile
