### ISSUE TITLE
Role not compatible w/ EL8 anymore b/c of requiring podman 4.2

### ISSUE THREAD

**Issue by cfelder** [linux-system-roles/podman#22]
podman 4.2 is not included in EL8. This role is not compatible anymore, but it is listing in EL8 in the galaxy meta though.

https://github.com/linux-system-roles/podman/blob/c4566b14d5248d2973b56d1c3e5182d62b905f1f/meta/main.yml#L17

I would prefer if EL8 can be included in the supported systems.

Is there currently any show stopper for running this w/ podman 4.1?

**Comment by richm** [comment]
> podman 4.2 is not included in EL8. This role is not compatible anymore, but it is listing in EL8 in the galaxy meta though.

podman 4.2 will be included with EL 8.7 (and EL 9.1)

> 
> https://github.com/linux-system-roles/podman/blob/c4566b14d5248d2973b56d1c3e5182d62b905f1f/meta/main.yml#L17

unfortunately the galaxy meta data does not provide the necessary granularity to say EL8.7 or later

> 
> I would prefer if EL8 can be included in the supported systems.
> 
> Is there currently any show stopper for running this w/ podman 4.1?

Yes.  podman < 4.2 does not have the support for `play kube` and `kube play` that the role uses.

**Comment by cfelder** [comment]
> Yes. podman < 4.2 does not have the support for `play kube` and `kube play` that the role uses.

``podman-play-kube`` is supported for a long time, but I am not aware of the opposite form ``kube play``.

I am looking forward to podman 4.2 landing in EL8.7.

**Comment by richm** [comment]
> > Yes. podman < 4.2 does not have the support for `play kube` and `kube play` that the role uses.
> 
> `podman-play-kube` is supported for a long time, but I am not aware of the opposite form `kube play`.

@vrothberg what is the salient feature of `podman-play-kube` that is supported only in 4.2?

> 
> I am looking forward to podman 4.2 landing in EL8.7.

**Comment by vrothberg** [comment]
> > `podman-play-kube` is supported for a long time, but I am not aware of the opposite form `kube play`.

They are the same command.  We added a `podman kube` command with v4.2 which lists all kube-related commands.  `play kube` and `generate kube` are now aliases to the `kube *` commands.  Naming is difficult :)
 
> @vrothberg what is the salient feature of `podman-play-kube` that is supported only in 4.2?

Running K8s YAML in systemd: https://www.redhat.com/sysadmin/kubernetes-workloads-podman-systemd
