### ISSUE TITLE
Feature request: Podman network support

### ISSUE THREAD

**Issue by andsky1234** [linux-system-roles/podman#42]
### Problem
---
On current version of the system role there is no way to configure which network to run the pods on. My problem is that dns resolution between pods doesn't work for me on RHEL 8.6 and podman 4.2. It does work on Fedora 37 which has podman 4.3 which adds a default podman-kube network but I stilll can not add any custom networks using this role.

### Desired solution
---
It would be nice to pass a variable to the role specifying a network name to use. The role would take care of creating the network if it doesn't exist and attach the pods to it.

**Comment by benblasco** [comment]
This could probably be extended to apply to any arbitrary parameter that is ultimately passed to the containers.podman.podman_play command, such as `--userns=mode` or `--tls-verify` etc.  However I believe that this would require some changes to the containers.podman.podman_play module itself to support this functionality.  Thoughts @briansmith0 @rhatdan ?

**Comment by benblasco** [comment]
This is relevant to my broader comment.  Happy to create a new issue if deemed to be a different problem to solve.

https://github.com/containers/ansible-podman-collections/issues/544

**Comment by briansmith0** [comment]
@vrothberg if the role were to support Quadlet, would it address this?

**Comment by vrothberg** [comment]
> @vrothberg if the role were to support Quadlet, would it address this?

Yes, Quadlet supports that.  `podman kube play` has a `--network` flag which allows for doing that when using K8s YAML, which in theory could be exposed by the role without Quadlet.

**Comment by richm** [comment]
https://github.com/linux-system-roles/podman/pull/78
