### ISSUE TITLE
Feature Request: Allow FreeIPA/IdM provided subuid and subgid

### ISSUE THREAD

**Issue by mhjacks** [linux-system-roles/podman#68]
FreeIPA/IdM now support distribution of subuid and subgid; if the environment is setup this way it is mutually exclusive of providing subuid/subgid via the files in /etc. Thus with the current approach to user/group handling, the role would fail.

A program called "getsubids" exists that can query for a given user or group subids ranges. Use of this technique would work for both file-provided IDs and ipa-provided ids.

Would the project be interested in an patch to handling users and groups that would use getsubids in preference to inspecting the files?

**Comment by mhjacks** [comment]
I use it primarily on Fedora and CentOS stream where it works well on f37+, c8s and c9s. It should also work on Debian (testing) and Ubuntu 22.04 (I think - I can test that); Freeipa-provided subids work on OpenSUSE 15.4, which has podman 4.4, but an older version of shadow so it does not have the getsubids binary) .  I don't know about podman quarkus functionality at all; my guess is it would be unrelated. I can do some research on the deb-derived systems in easy reach and let you know. (It seems it works for the soon-to-be-released bookworm, which will have podman 4.3; it does not work with Ubuntu Jammy which has 3.4.4)

**Comment by mhjacks** [comment]
It might be reasonable to try calling getsubids and if that fails to fallback to the file check, perhaps? I imagine the "normal" case for non-RedHat will continue to be /etc/sub{u,g}id for some time so I definitely think that path should still be supported

**Comment by richm** [comment]
> It might be reasonable to try calling getsubids and if that fails to fallback to the file check, perhaps?

Yes, sounds good.

> I imagine the "normal" case for non-RedHat will continue to be /etc/sub{u,g}id for some time so I definitely think that path should still be supported

ok

**Comment by richm** [comment]
@mhjacks see https://github.com/linux-system-roles/podman/pull/86

**Comment by mhjacks** [comment]
Yes, that looks entirely reasonable. Thanks for the heads up! That PR will definitely satisfy this feature request.

**Comment by richm** [comment]
> Yes, that looks entirely reasonable. Thanks for the heads up! That PR will definitely satisfy this feature request.

Thanks.  Are you able to test this directly from github, or do you require a release to Galaxy?

**Comment by mhjacks** [comment]
I can test from github. I've got the role installed from your branch and will report testing results today.
