### ISSUE TITLE
Unable to use podman_registries_conf to set unqualified-search-registries

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/podman#75]
I'm trying to use the podman_registries_conf variable to set the unqualified-search-registries setting:

```
    podman_registries_conf:
      unqualified-search-registries: ["registry.access.redhat.com"]
```

I would expect this to create the /etc/containers/registries.conf.d/50-systemroles.conf with the following:

`unqualified-search-registries = ["registry.access.redhat.com"]
`

However, the role fails when run:

```
TASK [redhat.rhel_system_roles.podman : Update registries config file] **************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'list object' has no attribute 'registry.access.redhat.com'
fatal: [rhel9-server1.example.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'registry.access.redhat.com'"}
```

It appears that the role only supports configuring podman_registries_conf options that are under a namespace such as:

```
[namespace]
option = value
```

However, the unqualified-search-registries setting is a global setting that isn't under a namespace.  For more info, see `man containers-registries.conf`

**Comment by briansmith0** [comment]
Created a BZ regarding this:  https://bugzilla.redhat.com/show_bug.cgi?id=2211984

**Comment by richm** [comment]
https://github.com/linux-system-roles/podman/pull/83
